version: "3.9"

services:
  database:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: db-visualizer-sample-db
    env_file:
      - ../local.env
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - .:/var/app
